# 데이터 핸들링

### 1. 데이터 합치기

In [1]:
import pandas as pd
import numpy as np

#### default inner join
    - inner join     pd.merge(df1, df2)
    - outer join     pd.merge(df1, df2, how = 'outer')
    - left join      pd.merge(df1, df2, how = 'left')
    - right join     pd.merge(df1, df2, how = 'right')

#### 1.1 테이블의 칼럼명이 같은 경우

In [2]:
df1 = pd.DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'a', 'b'], 'data1': range(7)})
df1

key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   a      5
6   b      6

In [3]:
df2 = pd.DataFrame({'key': ['a', 'b', 'd'],'data2': range(3)})
df2

key  data2
0   a      0
1   b      1
2   d      2

In [4]:
pd.merge(df1, df2)

key  data1  data2
0   b      0      1
1   b      1      1
2   b      6      1
3   a      2      0
4   a      4      0
5   a      5      0

어떤 칼럼을 기준으로 병합할 것인지 명시하지 않으면, merge함수는 겹치는 칼럼을 키로 사용

In [5]:
pd.merge(df1, df2, on='key')

key  data1  data2
0   b      0      1
1   b      1      1
2   b      6      1
3   a      2      0
4   a      4      0
5   a      5      0

#### 1.2 테이블의 칼럼명이 다른 경우

In [6]:
df3 = pd.DataFrame({'lkey': ['b', 'b', 'a', 'c', 'a', 'a', 'b'], 'data1': range(7)})
df3

lkey  data1
0    b      0
1    b      1
2    a      2
3    c      3
4    a      4
5    a      5
6    b      6

In [7]:
df4 = pd.DataFrame({'rkey': ['a', 'b', 'd'], 'data2': range(3)})
df4

rkey  data2
0    a      0
1    b      1
2    d      2

In [8]:
pd.merge(df3, df4, left_on = 'lkey', right_on = 'rkey')

lkey  data1 rkey  data2
0    b      0    b      1
1    b      1    b      1
2    b      6    b      1
3    a      2    a      0
4    a      4    a      0
5    a      5    a      0

key로 사용할 칼럼명을 각각 지정

#### 1.3 조인 조건의 변경

In [9]:
pd.merge(df1, df2, how='outer')

key  data1  data2
0   b    0.0    1.0
1   b    1.0    1.0
2   b    6.0    1.0
3   a    2.0    0.0
4   a    4.0    0.0
5   a    5.0    0.0
6   c    3.0    NaN
7   d    NaN    2.0

In [10]:
df1 = pd.DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'b'], 'data1': range(6)})
df1

key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   b      5

In [11]:
df2 = pd.DataFrame({'key': ['a', 'b', 'a', 'b', 'd'],'data2': range(5)})
df2

key  data2
0   a      0
1   b      1
2   a      2
3   b      3
4   d      4

In [12]:
pd.merge(df1, df2, on='key', how='left')

key  data1  data2
0    b      0    1.0
1    b      0    3.0
2    b      1    1.0
3    b      1    3.0
4    a      2    0.0
5    a      2    2.0
6    c      3    NaN
7    a      4    0.0
8    a      4    2.0
9    b      5    1.0
10   b      5    3.0

In [16]:
left_df = pd.DataFrame({'key': ['a', 'b', 'a', 'a', 'b', 'c'],   'value': range(6)})
left_df

key  value
0   a      0
1   b      1
2   a      2
3   a      3
4   b      4
5   c      5

In [17]:
right_df = pd.DataFrame({'group_val': [3.5, 7]}, index=['a', 'b'])
right_df

group_val
a        3.5
b        7.0

In [18]:
pd.merge(left_df, right_df, left_on='key', right_index=True)

key  value  group_val
0   a      0        3.5
2   a      2        3.5
3   a      3        3.5
1   b      1        7.0
4   b      4        7.0

Merge하려는 키가 DataFrame의 색인일 경우 옵션을 지정해 해당 색인을 키로 사용할 수 있음

In [ ]:
pd.merge(left_df, right_df, left_on='key', right_index=True, how='outer') 

In [19]:
left_df2 = pd.DataFrame({'data': np.arange(5.), 
                         'key1': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada'], 
                         'key2': [2000, 2001, 2002, 2001, 2002]})
left_df2

data    key1  key2
0   0.0    Ohio  2000
1   1.0    Ohio  2001
2   2.0    Ohio  2002
3   3.0  Nevada  2001
4   4.0  Nevada  2002

In [20]:
right_df2 = pd.DataFrame(np.arange(12).reshape((6, 2)), 
                         index=[['Nevada', 'Nevada', 'Ohio', 'Ohio', 'Ohio', 'Ohio'], 
                                [2001, 2000, 2000, 2000, 2001, 2002]], 
                         columns=['event1', 'event2'])
right_df2

event1  event2
Nevada 2001       0       1
       2000       2       3
Ohio   2000       4       5
       2000       6       7
       2001       8       9
       2002      10      11

In [21]:
pd.merge(left_df2, right_df2, left_on=['key1', 'key2'], right_index=True)

data    key1  key2  event1  event2
0   0.0    Ohio  2000       4       5
0   0.0    Ohio  2000       6       7
1   1.0    Ohio  2001       8       9
2   2.0    Ohio  2002      10      11
3   3.0  Nevada  2001       0       1

계층 색인된 데이터의 경우, 리스트로 여러 개의 칼럼을 지정해서 Merge 해야 함

In [22]:
pd.merge(left_df2, right_df2, left_on=['key1', 'key2'], right_index=True, how = 'outer')

data    key1  key2  event1  event2
0   0.0    Ohio  2000     4.0     5.0
0   0.0    Ohio  2000     6.0     7.0
1   1.0    Ohio  2001     8.0     9.0
2   2.0    Ohio  2002    10.0    11.0
3   3.0  Nevada  2001     0.0     1.0
4   4.0  Nevada  2002     NaN     NaN
4   NaN  Nevada  2000     2.0     3.0

외부조인을 실행하여 합집합을 구한 결과

In [23]:
left_df3 = pd.DataFrame([[1., 2.], [3., 4.], [5., 6.]], 
                        index=['a', 'c', 'e'], 
                        columns=['Ohio', 'Nevada'])
left_df3

Ohio  Nevada
a   1.0     2.0
c   3.0     4.0
e   5.0     6.0

In [24]:
right_df3 = pd.DataFrame([[7., 8.], [9., 10.], [11., 12.], [13, 14]], 
                         index=['b', 'c', 'd', 'e'], 
                         columns=['Missouri', 'Alabama'])
right_df3

Missouri  Alabama
b       7.0      8.0
c       9.0     10.0
d      11.0     12.0
e      13.0     14.0

In [25]:
pd.merge(left_df3, right_df3, how='outer', left_index=True, right_index=True)

Ohio  Nevada  Missouri  Alabama
a   1.0     2.0       NaN      NaN
b   NaN     NaN       7.0      8.0
c   3.0     4.0       9.0     10.0
d   NaN     NaN      11.0     12.0
e   5.0     6.0      13.0     14.0

양쪽에 공통으로 있는 여러 색인을 merge 함

In [26]:
left_df3.join(right_df3, how='outer')

Ohio  Nevada  Missouri  Alabama
a   1.0     2.0       NaN      NaN
b   NaN     NaN       7.0      8.0
c   3.0     4.0       9.0     10.0
d   NaN     NaN      11.0     12.0
e   5.0     6.0      13.0     14.0

* numpy패키지를 이용한 데이터 합치기

In [27]:
arr = np.arange(12).reshape((3, 4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [28]:
np.concatenate([arr, arr], axis=1)

array([[ 0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11]])

In [29]:
s1 = pd.Series([0, 1], index=['a', 'b'])

In [30]:
s2 = pd.Series([2, 3, 4], index=['c', 'd', 'e'])

In [31]:
s3 = pd.Series([5, 6], index=['f', 'g'])

In [32]:
pd.concat([s1, s2, s3])

a    0
b    1
c    2
d    3
e    4
f    5
g    6
dtype: int64

In [33]:
pd.concat([s1, s2, s3], axis=1)

0    1    2
a  0.0  NaN  NaN
b  1.0  NaN  NaN
c  NaN  2.0  NaN
d  NaN  3.0  NaN
e  NaN  4.0  NaN
f  NaN  NaN  5.0
g  NaN  NaN  6.0

In [34]:
a = pd.Series([np.nan, 2.5, np.nan, 3.5, 4.5, np.nan], index=['f', 'e', 'd', 'c', 'b', 'a'])
a

f    NaN
e    2.5
d    NaN
c    3.5
b    4.5
a    NaN
dtype: float64

In [35]:
b = pd.Series(np.arange(len(a), dtype=np.float64), index=['f', 'e', 'd', 'c', 'b', 'a'])
b

f    0.0
e    1.0
d    2.0
c    3.0
b    4.0
a    5.0
dtype: float64

In [36]:
b[-1] = np.nan
b

f    0.0
e    1.0
d    2.0
c    3.0
b    4.0
a    NaN
dtype: float64

In [37]:
np.where(pd.isnull(a), b, a)

array([0. , 2.5, 2. , 3.5, 4.5, nan])

### 2. 재형성(reshape)과 피벗(pivot)
* stack : 데이터의 칼럼을 로우로 피벗 또는 회전
* unstack : 로우를 칼럼으로 피벗

In [38]:
data = pd.DataFrame(np.arange(6).reshape((2, 3)),
                    index=pd.Index(['Ohio', 'Colorado'], name='state'),
                    columns=pd.Index(['one', 'two', 'three'], name='number'))
data

number    one  two  three
state                    
Ohio        0    1      2
Colorado    3    4      5

In [40]:
result = data.stack()
result

state     number
Ohio      one       0
          two       1
          three     2
Colorado  one       3
          two       4
          three     5
dtype: int32

In [41]:
result.unstack()

number    one  two  three
state                    
Ohio        0    1      2
Colorado    3    4      5

In [42]:
result.unstack(0)

state   Ohio  Colorado
number                
one        0         3
two        1         4
three      2         5

숫자를 전달해서 끄집어낼 단계를 지정할 수 있음

In [43]:
result.unstack('state')

state   Ohio  Colorado
number                
one        0         3
two        1         4
three      2         5

레벨 이름을 전달해서 끄집어낼 단계를 지정할 수 있음

<span style="color:red">※ 해당 레벨이 있는 모든 값이 하위 그룹에 속하지 않을 경우 unstack을 하게 되면 누락된 데이터가 발생할 수 있음</span>

In [44]:
s1 = pd.Series([0, 1, 2, 3], index=['a', 'b', 'c', 'd'])
s1

a    0
b    1
c    2
d    3
dtype: int64

In [45]:
s2 = pd.Series([4, 5, 6], index=['c', 'd', 'e'])
s2

c    4
d    5
e    6
dtype: int64

In [46]:
data2 = pd.concat([s1, s2], keys=['one', 'two'])
data2

one  a    0
     b    1
     c    2
     d    3
two  c    4
     d    5
     e    6
dtype: int64

In [47]:
data2.unstack()

a    b    c    d    e
one  0.0  1.0  2.0  3.0  NaN
two  NaN  NaN  4.0  5.0  6.0

In [48]:
data2.unstack().stack()

one  a    0.0
     b    1.0
     c    2.0
     d    3.0
two  c    4.0
     d    5.0
     e    6.0
dtype: float64

In [49]:
data2.unstack().stack(dropna=False)

one  a    0.0
     b    1.0
     c    2.0
     d    3.0
     e    NaN
two  a    NaN
     b    NaN
     c    4.0
     d    5.0
     e    6.0
dtype: float64